# kubelet daemon on a specific node manage static pod
# choose the node where to launch the static pod
# create directory /etc/static-pods/ and place the static pod yml there
# /etc/static-pods/static-pod.yaml and update path to kubelet service

apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    role: sp-role
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP

# open the service file under "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
# add this entry --pod-manifest-path=/etc/static-pod/
