# kubelet daemon on a specific node manage static pod
# choose the node where to launch the static pod
# create directory /etc/static-pods/ and place the static pod yaml there
# /etc/static-pods/static-pod.yaml and update path to kubelet service
# Run this command on the node where kubelet is running
#cat <<EOF >/etc/static-pods/static-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    role: sp-role
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
EOF
#Open the service file under "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
#add entry as mentioned below
--pod-manifest-path=/etc/static-pod/
